spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order-db
    username: postgres
    password: 123321
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-service-group
      auto-offset-reset: earliest

kafka:
  topics:
    promotions: promotions-events

server:
  tomcat:
    accesslog:
      enabled: true
      pattern: '%t %a "%r" %s %b %D'